### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by mschoenlaub** [compass-rs/sass-rs#10]
Hi guys,

just wanted to know whether this project is still being actively maintained by you. Otherwise I'd probably think of forking and maintaining it myself.

Cheers,
Manuel

**Comment by winding-lines** [comment]
I'd be happy to add you as an owner of you want to take over.

Marius
---

**Comment by Keats** [comment]
@mschoenlaub I have an update coming in (except for Windows where I didn't make it work yet)

**Comment by Keats** [comment]
Any change you can add me as a owner as well @winding-lines? Thanks!

**Comment by Keats** [comment]
@winding-lines could you make me an owner of both crates on crates.io as well?

**Comment by Keats** [comment]
@winding-lines could you make me an owner of both crates on crates.io as well? (http://doc.crates.io/crates-io.html#cargo-owner)

**Comment by winding-lines** [comment]
Done, many thanks for pushing this forward!

On Thu, Jul 13, 2017 at 7:16 AM, Vincent Prouillet <notifications@github.com
