### ISSUE TITLE
Fix build on OSX and Windows

### ISSUE THREAD

**Issue by Keats** [compass-rs/sass-rs#12]
# OSX
https://travis-ci.org/compass-rs/sass-rs/jobs/251018622

```
sass_rs-e84d3dc64d64c94e(2774,0x700000404000) malloc: *** error for object 0x10360d000: pointer being freed was not allocated

*** set a breakpoint in malloc_error_break to debug
```

# Windows
I don't know how to make the build work on AppVeyor

**Comment by Keats** [comment]
It looks like the OSX error only happens with `compile_string`

**Comment by mcgoo** [comment]
I'm taking a look at the Windows build.

**Comment by Keats** [comment]
Both are working, thanks!
