### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by raphaelcohn** [compass-rs/sass-rs#19]
In https://github.com/compass-rs/sass-rs/blob/master/src/bindings/options.rs, at line 64 - there's a call of `into_raw()`. As fall as I can tell in the underlying libsass code, it does not `free()` any strings passed in... Additionally, <https://doc.rust-lang.org/std/ffi/struct.CString.html#method.into_raw> says that calling code should not let C call `free()` on such a string if I understand it correctly...

**Comment by Keats** [comment]
Nice catch!
I think #20 should fix that but I'll think about it for a bit first
