### ISSUE TITLE
Doesn't compile on Windows

### ISSUE THREAD

**Issue by PhilipDaniels** [compass-rs/sass-rs#22]
Found this error when trying to compile Gutenberg on Windows. Running from "x64 Native Tools Command Prompt for VS2017" so that Windows can find `link.exe`, I get:

```
   Compiling serde_json v1.0.9
   Compiling num-iter v0.1.35
   Compiling log v0.3.9
   Compiling crossbeam-epoch v0.3.0
   Compiling syn v0.11.11
error: failed to run custom build command for `sass-sys v0.4.3`
process didn't exit successfully: `c:\Users\Phil\repos\gutenberg-fork\target\debug\build\sass-sys-cda42525225dc0fb\build-script-build` (exit code: 101)
--- stderr
fatal: Not a git repository (or any of the parent directories): .git
thread 'main' panicked at 'error running msbuild: Error { repr: Os { code: 2, message: "The system cannot find the file specified." } }', src\libcore\result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

Running with RUST_BACKTRACE=1 gives

```
error: failed to run custom build command for `sass-sys v0.4.3`
process didn't exit successfully: `c:\Users\Phil\repos\gutenberg-fork\target\debug\build\sass-sys-cda42525225dc0fb\build-script-build` (exit code: 101)
--- stderr
fatal: Not a git repository (or any of the parent directories): .git
thread 'main' panicked at 'error running msbuild: Error { repr: Os { code: 2, message: "The system cannot find the file specified." } }', src\libcore\result.rs:906:4
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:91
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:380
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:397
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:577
   4: std::panicking::begin_panic<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:538
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:522
   6: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:498
   7: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
   8: core::result::unwrap_failed<std::io::error::Error>
             at C:\projects\rust\src\libcore\macros.rs:23
   9: core::result::Result<std::process::Output, std::io::error::Error>::expect<std::process::Output,std::io::error::Error>
             at C:\projects\rust\src\libcore\result.rs:799
  10: build_script_build::compile
             at .\build.rs:57
  11: build_script_build::main
             at .\build.rs:91
  12: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:101
  13: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:51
  14: main
  15: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  16: BaseThreadInitThunk

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by Keats** [comment]
It does compile on Windows (appveyor works: https://github.com/compass-rs/sass-rs/blob/master/appveyor.yml) but I have absolutely no idea what exact dependencies are needed and no Windows machine to test sadly. If you manage to make it work, I'd really like a PR to add the info to the README since compiling sass-rs on Windows seems to be annoying.

**Comment by Keats** [comment]
@PhilipDaniels Did you manage to make it work?

**Comment by PhilipDaniels** [comment]
Sorry, I haven't tried, been busy with other things. It might help if you knew what build commands the appveyor runs?

**Comment by Keats** [comment]
The whole thing is in https://github.com/compass-rs/sass-rs/blob/master/appveyor.yml so absolutely nothing unusual apart from the git submodule. I guess the issue is getting the right dependencies used in the `Visual Studio 2013` image but I can't see anything about it from a run: https://ci.appveyor.com/project/Keats/sass-rs-rmnm5/branch/master/job/s58ed8l8hcs5gx9h

**Comment by ErichDonGubler** [comment]
To clarify, this issue is with the MSVC toolchain, and not Windows as a whole -- I can compile this and run the `compile_sass` example without any problems on the GNU toolchain, though I suspect some of my current setup might be needed to get it to work.

**Comment by mattico** [comment]
You should be able to solve this issue by running `cargo build` inside of a Visual studio tools command prompt. I solved a similar issue (it was trying to use VS2010 tools) by running inside of a VS2015 command prompt.

**Comment by ErichDonGubler** [comment]
@mattico: Hey, that works! Thanks for the tip. :)

For those hoping for some more concrete details, I had to do this to get it to work:

1. Open `Developer Command Prompt for <your installation version here>`.
2. Use these commands, filling in the dummy variables `gutenberg_directory`, `vs_version`, and `target_platform` as appropriate:

    ```bat
        cd %gutenberg_directory%

        REM Use this to change your target if you want -- you may not need it.
        C:\Program Files (x86)\Microsoft Visual Studio %vs_version%\VC\vcvarsall.bat %target_platform%
        REM Deleting `target` may not be necessary, but it was for me since I had some previously failed compiles for a different target.
        rd /s /q target

        cargo build
    ```

**Comment by PhilipDaniels** [comment]
@ErichDonGubler I believe running `vcvarsall.bat` manually as you did is equivalent to opening the `x64 Native Tools Command Prompt` from the menu. It runs it as the first step. I did try this originally and it didn't work. I tried again with the latest commit and got a similar error

```
error: failed to run custom build command for `sass-sys v0.4.4 (file:///C:/Users/Phil/repos/sass-rs/sass-sys)`
process didn't exit successfully: `c:\Users\Phil\repos\sass-rs\target\debug\build\sass-sys-1a4bc3ed75bd65ee\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'error running msbuild: Error { repr: Os { code: 2, message: "The system cannot find the file specified." } }', src\libcore\result.rs:916:5
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:56
   2: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:381
   3: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:577
   5: std::panicking::begin_panic<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:522
   7: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:498
   8: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
   9: core::result::unwrap_failed<std::io::error::Error>
             at C:\projects\rust\src\libcore\macros.rs:23
  10: core::result::Result<std::process::Output, std::io::error::Error>::expect<std::process::Output,std::io::error::Error>
             at C:\projects\rust\src\libcore\result.rs:809
  11: build_script_build::compile
             at .\build.rs:78
  12: build_script_build::main
             at .\build.rs:120
  13: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  14: std::panicking::try::do_call<closure,i32>
             at C:\projects\rust\src\libstd\panicking.rs:476
  15: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:101
  16: std::rt::lang_start_internal
             at C:\projects\rust\src\libstd\rt.rs:50
  17: std::rt::lang_start<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  18: main
  19: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  20: BaseThreadInitThunk
```

Other info
* I've tried it on nightly and stable and doing `rustup update`.
* I do have VS2015 and VS2017 installed
* I can open the libsass sln file in VS2017 and build it out of the box
* Though I do get this upgrade warning when I do that

![libsass_sln_upgrade](https://user-images.githubusercontent.com/1809220/37622714-567dad54-2bba-11e8-8a62-2db69e244559.png)

**Comment by ErichDonGubler** [comment]
@PhilipDaniels: The line that's failing in `sass-sys`'s `build.rs` is [here](https://github.com/compass-rs/sass-rs/blob/master/sass-sys/build.rs#L78) -- looks like it can't find your `MSBuild.exe`? Can you run `msbuild` from your native tools prompt?

**Comment by PhilipDaniels** [comment]
Yep:

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>msbuild
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
```

I wonder if `let r = gcc::windows_registry::find(target.as_str(), "msbuild.exe")` is getting confused by old installs, SDKs etc. This is a 5 year old Windows machine which has got a lot of MS stuff installed on it.

**Comment by Geobert** [comment]
It seems that sass-rs can't build with VS2017:
https://ci.appveyor.com/project/tak1n/cobalt-rs/build/1.0.781#L272

**Comment by Keats** [comment]
On the related thread on cobalt, you say you are having errors with VS2015 and syntect, but the CI for Gutenberg is using VS2015 and doesn't have issues afaik

Either way, I don't have access to a Windows dev machine so I can't help for that

**Comment by Geobert** [comment]
Maybe a solution would be to call devenv.exe /upgrade on the `sln`
https://blogs.msdn.microsoft.com/vcblog/2010/03/25/to-the-command-line-enthusiasts-some-quick-know-hows-for-upgrading-to-vs-2010/

**Comment by Geobert** [comment]
I've suggested a PR for this: https://github.com/compass-rs/sass-rs/pull/25

**Comment by Geobert** [comment]
Any plan to do a 0.2.2 release with the VS2017 support? Or are we waiting for https://github.com/rust-lang/rust/issues/50778 to be solved? I'm not sure it's fixed, but since 1.27 I don't see this any more on my computer.

**Comment by Keats** [comment]
sass-sys got a release in may, I don't think I need to publish sass-rs no?

**Comment by Geobert** [comment]
Oh I didn't notice for sass-sys! That's why my tests on appveyor are working with the current version of sass-rs ^^' stupid me :p
