### ISSUE TITLE
Readme shows wrong function signatures

### ISSUE THREAD

**Issue by Boscop** [compass-rs/sass-rs#33]
> sass-rs exposes 2 functions that are self-explanatory:
compile_file(path: &str, options: Options)
compile_file<P: AsRef<Path>>(path: P, options: Options)

The first one should be `compile_string(content: &str, options: Options)`.

It would also make sense to include the return types in the signatures..

**Comment by Keats** [comment]
Hmm I should just remove that bit from the README and  point to the api docs, they will be up-to-date...
