### ISSUE TITLE
Document OutputStyle

### ISSUE THREAD

**Issue by Korvox** [compass-rs/sass-rs#38]
While it _sounded_ intuitive in the documentation, I still felt compelled to make sure the four styles were what I expected them to be and ended up here:

https://web-design-weekly.com/2014/06/15/different-sass-output-styles/

Would you like some inline documentation examples of what the styles look like? Or maybe even just a disclaimer "it is what it says on the tin". Compressed vs Compact is fairly ambiguous if you haven't tested the settings by hand on your own.

**Comment by Keats** [comment]
Yep go ahead! Maybe just point to https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style ?
