### ISSUE TITLE
Not building under Android termux

### ISSUE THREAD

**Issue by fneddy** [compass-rs/sass-rs#48]
The library is not building under Android Termux.

The reason is that Termux uses `-lc++` to link to the c++ library but sass-sys will try to link with `-llibc++`. The linker flags are currently hard tied to the target platform in the [build.rs](../blob/master/sass-sys/build.rs#L90). There are Linux platforms that use `-lc++` and also bsds that use `-llibc++`. 

I changed the [build.rs](https://github.com/fneddy/sass-rs/blob/master/sass-sys/build.rs#L71) so that it tries to link the different possibilities and than selects the one that is available. If you like I can open a pull request.

**Comment by Keats** [comment]
I've never heard of termux but please do make a PR!

**Comment by Keats** [comment]
Released in 0.4.12
