### ISSUE TITLE
Starts dozens (sometimes hundreds) of build processes

### ISSUE THREAD

**Issue by nic-hartley** [compass-rs/sass-rs#53]
When building `sass-sys`, a _huge_ number of `cc1plus` processes are started, to the point that my entire computer starts to lag and every CPU gets pinned at 100%. The number doesn't change even if I specify `MAKE_LIBSASS_JOBS`.

The title says "sometimes" because the number of jobs changes over time, possibly as `make` starts compiling new files/finishes with old ones, and I couldn't get a consistent number. It was always in the same range, though.

At least ctrl+C works fairly quickly to kill the entire bundle.

Platform: WSL (Ubuntu); rustc 1.36.0

**Comment by Keats** [comment]
That's weird, can you try to run the commands from sass-sys build.rs manually to see what happens?

**Comment by nic-hartley** [comment]
@Keats I can certainly try. I'll edit this comment with my results in a moment.

**Comment by richardwhiuk** [comment]
I think https://github.com/sass/libsass/blob/4d229af5500be1023883c38c4a675f0ed919839d/Makefile#L22 is responsible, and is overriding the `--jobs` argument in some cases...

**Comment by richardwhiuk** [comment]
```
sass-rs = "0.2"
sass-sys = "=0.4.8"
```

is sufficient to avoid this.

**Comment by richardwhiuk** [comment]
That's reverted in https://github.com/sass/libsass/pull/2977, so the next step is an updated version of sass-sys.

**Comment by Keats** [comment]
Good find! I've asked if they can cut a release and I'll update asap

**Comment by nic-hartley** [comment]
Wow, I... genuinely didn't expect this to move so fast. Is there any ETA, or will it just happen whenever the libsass folks cut their next release?

**Comment by Keats** [comment]
They just released a new version, can anyone try https://github.com/compass-rs/sass-rs/pull/57 to see if it fixes it?
