### ISSUE TITLE
location override for system-provided libsass

### ISSUE THREAD

**Issue by ng-0** [compass-rs/sass-rs#54]
Hi, your libsass crate got pulled in in my work while packaging zola for pkgsrc.

Are you open to add an option to use a system provided, already compiled, libsass? This would make it a bit easier for the packaging.

**Comment by Keats** [comment]
Isn't that line in the build.rs https://github.com/compass-rs/sass-rs/blob/master/sass-sys/build.rs#L193 doing that already?

**Comment by ng-0** [comment]
Oh, missed this. Hm. Then I have to find another possibility why libsassl.so.1 doesn't end up in the linked libraries.
