### ISSUE TITLE
Fail to compile for Linux on Travis-CI

### ISSUE THREAD

**Issue by Geobert** [compass-rs/sass-rs#55]
We're having issue with `sass-sys` only on Linux:
https://travis-ci.org/cobalt-org/cobalt.rs/jobs/569981128#L791

I've tried 0.4.13 as well:
https://travis-ci.org/Geobert/cobalt.rs/jobs/571738194#L580

The creepy part being:
```
thread 'main' panicked at 'Build error:

STDERR:virtual memory exhausted: Cannot allocate memory

g++: internal compiler error: Killed (program cc1plus)
```

**Comment by Keats** [comment]
Maybe it could be linked to #53 somehow? FYI the builds for this crate work well in Travis so it's even weirder

**Comment by Geobert** [comment]
It can be, all these processes burning the RAM? I've seen that you don't have the issue with the crate, but as it's not compiling as much crates as cobalt, maybe that's the difference?

**Comment by Keats** [comment]
It also is not posing issues on Azure Pipelines for Zola fyi

**Comment by Geobert** [comment]
Indeed, it's working on AzDO, do we want to sort this out with Travis or it's a limitation of their free plan?

**Comment by Keats** [comment]
It might be related to https://github.com/compass-rs/sass-rs/issues/53

**Comment by Keats** [comment]
Closing unless it's reproducible on the latest version.
