### ISSUE TITLE
Build fails on FreeBSD due to standard C++ library detection failure

### ISSUE THREAD

**Issue by grembo** [compass-rs/sass-rs#66]
Build on FreeBSD fails during linking because it cannot find libstdc++.

This is due to the way the detection mechanism works in build.rs:

https://github.com/compass-rs/sass-rs/blob/79e16d7a4ca197fac35e128e0c80af04215c4d19/sass-sys/build.rs#L135-L146

The problem is that `cc` (which is clang) has a special logic for "-lstdc++", which means that it always passes, e.g.

```
# echo "int main {}" | cc -xc++ -lstdc++ -
# echo $?
0
#
```

When invoking `c++` instead of `cc`, the resulting executable is still linked agains _libc++_ and not _libstdc++_. A detection mechanism based on `c++` would need to use the _-stdlib_ parameter to actually make a difference, e.g. `c++ -stdlib=libstdc++`, I'm not sure if this is portable. This might also affect darwin (but there the first option probed for usually works).

I'm happy to submit a patch, but it would be good to determine the best way to work around the issue first - I'm inclined to simply add a (Free)BSD specific patch that puts _libc++_ to the top of options probed.

**Comment by Keats** [comment]
Released
