### ISSUE TITLE
sass-sys fails to build when git is not present in build chroot

### ISSUE THREAD

**Issue by teknokatze** [compass-rs/sass-rs#69]
Hi,

our builder regularly crashes in sandboxed builds on www/zola.
The cause of it seems to be around this line: https://github.com/compass-rs/sass-rs/blob/master/sass-sys/build.rs#L56

The zola release we are packaging is on sass-sys 0.4.18 but this is still around in HEAD of sass-sys.

Fix would be to not rely on the existence of git or the ability to get data over the network, no reasonable package manager will allow this.

**Comment by Keats** [comment]
I'm not going to copy the libsass repo in here though. We can try to revert https://github.com/compass-rs/sass-rs/pull/61 and see what happens.

**Comment by teknokatze** [comment]
Okay, so when no network access happens it should be okay.

I have a rather basic understanding of Rust, not that much. But I think adjusting it to the point where not finding an executable named "git" does not result in an error but rather a warning (unless there's a mode where rustc does a warnings=error treatment) would be okay?

**Comment by Keats** [comment]
I think https://github.com/compass-rs/sass-rs/pull/70 should work? I don't think I can emit warnings though.

**Comment by teknokatze** [comment]
libsass is in the crate included, right? I only noticed this in the sandbox, but even outside of it we don't allow cargo or anyone else to fetch data after a certain point. So this looks okay in theory if crate excluded .git parts of libsass.
I only see ".github" in sass-sys/libsass/ directory of our pulled crates in the build, so the patch looks like it could work.

**Comment by Keats** [comment]
Yeah, I'm not too sure what Cargo packages in the crate. Let's see how it goes

**Comment by Keats** [comment]
0.4.20 pushed, I'll update Zola in a bit

**Comment by teknokatze** [comment]
Thanks!
