### ISSUE TITLE
Add maintenance status in the readme

### ISSUE THREAD

**Issue by cipriancraciun** [compass-rs/sass-rs#83]
In the last comment on #6, @Keats said that:
> [...] this crate is not maintained anymore as `libsass` is deprecated. [...]

Thus, if `sass-rs` is no longer being maintained, perhaps adding a notice banner on the readme would help users in search of a Rust SASS compiler to move to other alternatives (not that there are too many).

Also, given that there are commits in the repository which are not yet released, perhaps making a one last release on `crates.io`?

**Comment by Keats** [comment]
Done. All the commits should have been released, which ones are not?

**Comment by cipriancraciun** [comment]
> All the commits should have been released, which ones are not?

I've looked at the latest commit in the repository, and the date on the latest crate:
* <https://crates.io/crates/sass-rs> (version `0.2.2`) -- latest release 2019-05-22;
* <https://github.com/compass-rs/sass-rs/commits/master> -- latest commit in 2021-06-01;  (although, now that I look more closely, it seems to be related to the `-sys` library, and looking at the history of `src` it does seem to be no other updates;)

Thus just asking to be sure we have the latest version in `crates.io`.

Thanks.

**Comment by Keats** [comment]
The last changes were for https://crates.io/crates/sass-sys as you say, so we should be fine
